version: '3.7'

services:
    db:
        image: postgres:15.2
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - backend
            
    redis:
        image: redis:5.0
        restart: always
        environment:
            # Пароль для Redis, используется в команде запуска
            REDIS_PASSWORD: '${REDIS_PASSWORD}'
        # Порт для доступа к Redis с хоста, загружается из .env
        ports:
            - '${REDIS_PORT}:6379'
        command: redis-server --requirepass "${REDIS_PASSWORD}" # Используем переменную из .env
        volumes:
            - redis_data:/data
        networks:
            - backend

volumes:
    postgres_data:
    redis_data:

networks:
    backend:
